services:
  php:
    user: "${UID:-1000}:${GID:-1000}"
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: shanbora_php
    volumes:
      - ./:/var/www/shanbora:cached
      - composer_cache:/root/.composer
    environment:
      - DATABASE_URL=mysql://project:project@db_default:3306/shanbora?serverVersion=mariadb-11.4.9
    depends_on:
      db_default:
        condition: service_healthy
    networks:
      - symfony

  nginx:
    image: nginx:alpine
    container_name: shanbora_nginx
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/shanbora/public:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - symfony

  db_default:
    image: mariadb:11.4.9
    container_name: shanbora_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shanbora
      MYSQL_USER: project
      MYSQL_PASSWORD: project
    ports:
      - "3306:3306"
    volumes:
      - db_default:/var/lib/mysql
    networks:
      - symfony
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 3s
      retries: 10

  node:
    image: node:20.19.4-alpine
    container_name: shanbora_node
    working_dir: /var/www/shanbora
    volumes:
      - ./:/var/www/shanbora:cached
      - node_modules:/var/www/shanbora/node_modules
    command: sh -c "yarn install && chown -R ${UID:-1000}:${GID:-1000} /var/www/shanbora/node_modules && yarn watch"
    networks:
      - symfony

networks:
  symfony:
    driver: bridge

volumes:
  db_default:
  composer_cache:
  node_modules:
